"""Perfil de fuentes y registro de cadencias para el Observatorio ENSO Perú.

Define SourceProfile para cada fuente oficial, con metadatos de cadencia,
ventana de publicación, SLO de frescura, y nivel de autoridad.

Tres capas temporales:
  - RAPID_OBSERVATIONAL: observaciones rápidas (diarias/semanales)
  - OPERATIONAL_INDEX: índices operacionales (mensuales/estacionales)
  - OFFICIAL_AUTHORITY: comunicados oficiales (event-driven)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class AuthorityLevel(str, Enum):
    RAPID_OBSERVATIONAL = "rapid_observational"
    OPERATIONAL_INDEX = "operational_index"
    OFFICIAL_AUTHORITY = "official_authority"


class OperationalRisk(str, Enum):
    LOW_STRUCTURED = "LOW_STRUCTURED_OPERATIONAL"
    MEDIUM_IRREGULAR = "MEDIUM_IRREGULAR_OR_LEGACY"
    HIGH_HTML = "HIGH_HTML_OR_DASHBOARD"
    HIGH_DOCUMENT = "HIGH_DOCUMENT_ONLY"
    EXPERIMENTAL = "EXPERIMENTAL"
    REJECTED = "REJECTED"


@dataclass(frozen=True)
class SourceProfile:
    """Contrato versionado de una fuente científica."""
    source_id: str
    institution: str
    product: str
    canonical_url: str
    access_url: str
    access_method: str  # 'csv', 'ascii', 'opendap_ascii', 'html_parse'
    format: str
    authority_level: AuthorityLevel
    supported_metric_ids: tuple[str, ...]
    region: str
    units: str
    climatology: str
    temporal_resolution: str  # 'daily', 'weekly', 'monthly', 'seasonal'
    expected_cadence: str  # 'daily', 'weekly', 'monthly'
    expected_release_window: str  # descripción humana
    typical_lag: str  # '1-2 days', '2-5 days'
    freshness_slo: str  # '7 days', '45 days'
    stale_after: str  # '14 days', '60 days'
    revision_window: str
    preliminary_policy: str
    license: str
    attribution: str
    request_budget: int  # max requests per run
    timeout: float  # seconds
    max_retries: int
    fallback_source_ids: tuple[str, ...] = ()
    operational_risk: OperationalRisk = OperationalRisk.LOW_STRUCTURED
    last_verified_at: str = ""
    unresolved_limitations: str = ""


# ----------------------------------------------------------------------------
# Registro de fuentes verificadas
# ----------------------------------------------------------------------------
SOURCES: dict[str, SourceProfile] = {
    # --- Capa rápida observacional ---
    "noaa-ncei-oisst-daily-preliminary": SourceProfile(
        source_id="noaa-ncei-oisst-daily-preliminary",
        institution="NOAA / NCEI",
        product="Daily OISST v2.1 preliminary regional subsets",
        canonical_url="https://www.ncei.noaa.gov/products/optimum-interpolation-sst",
        access_url=(
            "https://www.ncei.noaa.gov/erddap/griddap/"
            "ncdc_oisst_v2_avhrr_prelim_by_time_zlev_lat_lon"
        ),
        access_method="erddap_griddap_csv",
        format="csv_grid_subset",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("nino12_daily_observation", "nino34_daily_observation"),
        region="Niño 1+2 and Niño 3.4 bounded subsets; longitude 0–360",
        units="degC (sst, anom, err)",
        climatology="1971-2000 anomaly climatology (dataset attribute)",
        temporal_resolution="daily",
        expected_cadence="daily",
        expected_release_window="Daily after upstream satellite/in-situ processing",
        typical_lag="1-2 days",
        freshness_slo="4 days",
        stale_after="7 days",
        revision_window="Superseded by final OISST after quality control",
        preliminary_policy="Always label PRELIMINARY until reconciled with final dataset",
        license="Public domain (NOAA)",
        attribution="NOAA/NCEI Daily OISST v2.1 preliminary",
        request_budget=4,
        timeout=45.0,
        max_retries=3,
        fallback_source_ids=("noaa-ncei-oisst-daily-final", "noaa-cpc-wksst"),
        operational_risk=OperationalRisk.LOW_STRUCTURED,
        last_verified_at="2026-08-07",
        unresolved_limitations="Observational context only; does not replace ICEN, RONI, or an official alert.",
    ),
    "noaa-ncei-oisst-daily-final": SourceProfile(
        source_id="noaa-ncei-oisst-daily-final",
        institution="NOAA / NCEI",
        product="Daily OISST v2.1 final regional subsets",
        canonical_url="https://www.ncei.noaa.gov/products/optimum-interpolation-sst",
        access_url=(
            "https://www.ncei.noaa.gov/erddap/griddap/"
            "ncdc_oisst_v2_avhrr_by_time_zlev_lat_lon"
        ),
        access_method="erddap_griddap_csv",
        format="csv_grid_subset",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("nino12_daily_observation", "nino34_daily_observation"),
        region="Niño 1+2 and Niño 3.4 bounded subsets; longitude 0–360",
        units="degC (sst, anom, err)",
        climatology="1971-2000 anomaly climatology (dataset attribute)",
        temporal_resolution="daily",
        expected_cadence="daily with finalization lag",
        expected_release_window="Daily, following preliminary quality-control window",
        typical_lag="approximately 2 weeks (observed 15 days on 2026-08-07)",
        freshness_slo="21 days",
        stale_after="30 days",
        revision_window="Final product; upstream corrections remain possible",
        preliminary_policy="FINAL; reconcile same valid day by replacing preliminary record",
        license="Public domain (NOAA)",
        attribution="NOAA/NCEI Daily OISST v2.1 final",
        request_budget=4,
        timeout=45.0,
        max_retries=3,
        fallback_source_ids=("noaa-cpc-wksst",),
        operational_risk=OperationalRisk.LOW_STRUCTURED,
        last_verified_at="2026-08-07",
    ),
    "pmel-tao-daily-d20": SourceProfile(
        source_id="pmel-tao-daily-d20",
        institution="NOAA / PMEL",
        product="TAO/TRITON daily 20 °C isotherm depth (pmelTaoDyIso)",
        canonical_url="https://www.pmel.noaa.gov/tao/",
        access_url="https://data.pmel.noaa.gov/pmel/erddap/tabledap/pmelTaoDyIso.csv",
        access_method="erddap_tabledap_csv",
        format="csv_station_subset",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("d20_station_daily",),
        region="TAO/TRITON station observations; explicit station coverage required",
        units="m (ISO_6; QI_5006 quality flag)",
        climatology="N/A (observed depth, not anomaly)",
        temporal_resolution="daily",
        expected_cadence="daily",
        expected_release_window="Daily as station telemetry is processed",
        typical_lag="variable by station; latest catalog time verified 2026-07-03",
        freshness_slo="14 days",
        stale_after="35 days",
        revision_window="Quality-control revisions possible",
        preliminary_policy="Station data; display coverage and quality, corroboration only",
        license="Public domain (NOAA)",
        attribution="NOAA/PMEL TAO/TRITON",
        request_budget=2,
        timeout=45.0,
        max_retries=2,
        operational_risk=OperationalRisk.MEDIUM_IRREGULAR,
        last_verified_at="2026-08-07",
        unresolved_limitations="A buoy or changing station subset cannot replace the GODAS basin metric.",
    ),
    "pmel-tao-daily-wind": SourceProfile(
        source_id="pmel-tao-daily-wind",
        institution="NOAA / PMEL",
        product="TAO/TRITON daily surface wind (pmelTaoDyW)",
        canonical_url="https://www.pmel.noaa.gov/tao/",
        access_url="https://data.pmel.noaa.gov/pmel/erddap/tabledap/pmelTaoDyW.csv",
        access_method="erddap_tabledap_csv",
        format="csv_station_subset",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("surface_wind_station_daily",),
        region="TAO/TRITON stations; explicit station coverage required",
        units="m s-1 (WU_422, WV_423, WS_401 plus quality flags)",
        climatology="N/A (observed surface wind)",
        temporal_resolution="daily",
        expected_cadence="daily",
        expected_release_window="Daily as station telemetry is processed",
        typical_lag="variable by station",
        freshness_slo="14 days",
        stale_after="35 days",
        revision_window="Quality-control revisions possible",
        preliminary_policy="Corroboration only; never substitute for CPC 850 hPa wind",
        license="Public domain (NOAA)",
        attribution="NOAA/PMEL TAO/TRITON",
        request_budget=2,
        timeout=45.0,
        max_retries=2,
        operational_risk=OperationalRisk.MEDIUM_IRREGULAR,
        last_verified_at="2026-08-07",
        unresolved_limitations="Surface station wind is not the CPC 850 hPa regional index.",
    ),
    "noaa-cpc-wksst": SourceProfile(
        source_id="noaa-cpc-wksst",
        institution="NOAA / CPC",
        product="Weekly OISST Niño region SST/SSTA",
        canonical_url="https://www.cpc.ncep.noaa.gov/data/indices/",
        access_url="https://www.cpc.ncep.noaa.gov/data/indices/wksst9120.for",
        access_method="ascii",
        format="fixed_width",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("nino12_weekly", "nino34_weekly"),
        region="Niño 1+2, Niño 3, Niño 3.4, Niño 4",
        units="degC",
        climatology="1991-2020 baseline",
        temporal_resolution="weekly",
        expected_cadence="weekly",
        expected_release_window="Lunes (actualización semanal)",
        typical_lag="3-7 days",
        freshness_slo="14 days",
        stale_after="21 days",
        revision_window="1-2 weeks",
        preliminary_policy="Latest 1-2 weeks may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC OISST v2.1",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),

    # --- Capa de índices operacionales ---
    "noaa-psl-nino12": SourceProfile(
        source_id="noaa-psl-nino12",
        institution="NOAA / PSL",
        product="Niño 1+2 monthly SST anomaly",
        canonical_url="https://psl.noaa.gov/data/timeseries/month/data/nino12.long.anom.csv",
        access_url="https://psl.noaa.gov/data/timeseries/month/data/nino12.long.anom.csv",
        access_method="csv",
        format="csv",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("nino12",),
        region="Niño 1+2 (90°W-80°W, 10°S-0°)",
        units="degC",
        climatology="1991-2020",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Primera semana del mes siguiente",
        typical_lag="3-10 days",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="1-3 months",
        preliminary_policy="Latest month may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/PSL",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),
    "noaa-psl-nino34": SourceProfile(
        source_id="noaa-psl-nino34",
        institution="NOAA / PSL",
        product="Niño 3.4 monthly SST anomaly",
        canonical_url="https://psl.noaa.gov/data/timeseries/month/data/nino34.long.anom.csv",
        access_url="https://psl.noaa.gov/data/timeseries/month/data/nino34.long.anom.csv",
        access_method="csv",
        format="csv",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("nino34",),
        region="Niño 3.4 (170°W-120°W, 5°S-5°N)",
        units="degC",
        climatology="1991-2020",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Primera semana del mes siguiente",
        typical_lag="3-10 days",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="1-3 months",
        preliminary_policy="Latest month may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/PSL",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),
    "noaa-cpc-roni": SourceProfile(
        source_id="noaa-cpc-roni",
        institution="NOAA / CPC",
        product="RONI — Relative Oceanic Niño Index (official)",
        canonical_url="https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso/roni/",
        access_url="https://www.cpc.ncep.noaa.gov/data/indices/RONI.ascii.txt",
        access_method="ascii",
        format="ascii_seasonal",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("roni",),
        region="Niño 3.4 (170°W-120°W, 5°S-5°N) with tropical-mean adjustment",
        units="degC",
        climatology="1991-2020 (relative to tropical mean 15°S-15°N)",
        temporal_resolution="seasonal (overlapping 3-month: DJF, JFM, ...)",
        expected_cadence="monthly (with 3-month overlap)",
        expected_release_window="Primera quincena del mes siguiente",
        typical_lag="5-15 days",
        freshness_slo="60 days",
        stale_after="75 days",
        revision_window="1-3 months",
        preliminary_policy="Latest 1-2 seasons may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC RONI (Huang et al. baseline adaptativa)",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        fallback_source_ids=(),
        operational_risk=OperationalRisk.LOW_STRUCTURED,
        unresolved_limitations="RONI no es una media móvil simple de Niño 3.4; "
        "usa ERSST con ajuste de media tropical relativa. No debe calcularse "
        "como rolling mean de Niño 3.4.",
    ),
    "noaa-cpc-soi": SourceProfile(
        source_id="noaa-cpc-soi",
        institution="NOAA / CPC",
        product="Monthly SOI (Tahiti-Darwin standardized)",
        canonical_url="https://www.cpc.ncep.noaa.gov/data/indices/",
        access_url="https://www.cpc.ncep.noaa.gov/data/indices/soi",
        access_method="ascii",
        format="ascii_monthly",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("soi",),
        region="Tahiti-Darwin (escala de cuenca)",
        units="dimensionless (standardized)",
        climatology="Climatología estándar CPC",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Primera semana del mes siguiente",
        typical_lag="3-7 days",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="1-3 months",
        preliminary_policy="Latest month may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC SOI",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),
    "noaa-cpc-wpac850": SourceProfile(
        source_id="noaa-cpc-wpac850",
        institution="NOAA / CPC",
        product="850 hPa trade wind index — Western Pacific (135°E-180°W)",
        canonical_url="https://www.cpc.ncep.noaa.gov/data/indices/",
        access_url="https://www.cpc.ncep.noaa.gov/data/indices/wpac850",
        access_method="ascii",
        format="ascii_monthly",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("u850_wpac",),
        region="Western Pacific 135°E-180°W, 5°S-5°N",
        units="m/s (actual wind, not anomaly)",
        climatology="N/A (original data)",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Primera semana del mes siguiente",
        typical_lag="3-7 days",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="1-3 months",
        preliminary_policy="Latest month may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC 850 hPa trade wind indices",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),
    "noaa-cpc-cpac850": SourceProfile(
        source_id="noaa-cpc-cpac850",
        institution="NOAA / CPC",
        product="850 hPa trade wind index — Central Pacific (175°W-140°W)",
        canonical_url="https://www.cpc.ncep.noaa.gov/data/indices/",
        access_url="https://www.cpc.ncep.noaa.gov/data/indices/cpac850",
        access_method="ascii",
        format="ascii_monthly",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("u850_cpac",),
        region="Central Pacific 175°W-140°W, 5°S-5°N",
        units="m/s (actual wind, not anomaly)",
        climatology="N/A (original data)",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Primera semana del mes siguiente",
        typical_lag="3-7 days",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="1-3 months",
        preliminary_policy="Latest month may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC 850 hPa trade wind indices",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),
    "noaa-cpc-epac850": SourceProfile(
        source_id="noaa-cpc-epac850",
        institution="NOAA / CPC",
        product="850 hPa trade wind index — Eastern Pacific (135°W-120°W)",
        canonical_url="https://www.cpc.ncep.noaa.gov/data/indices/",
        access_url="https://www.cpc.ncep.noaa.gov/data/indices/epac850",
        access_method="ascii",
        format="ascii_monthly",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("u850_epac",),
        region="Eastern Pacific 135°W-120°W, 5°S-5°N",
        units="m/s (actual wind, not anomaly)",
        climatology="N/A (original data)",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Primera semana del mes siguiente",
        typical_lag="3-7 days",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="1-3 months",
        preliminary_policy="Latest month may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC 850 hPa trade wind indices",
        request_budget=5,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.LOW_STRUCTURED,
    ),
    "noaa-cpc-godas-d20": SourceProfile(
        source_id="noaa-cpc-godas-d20",
        institution="NOAA / PSL (GODAS)",
        product="D20 anomaly (dbss_obil isothermal layer depth) — Niño 3.4",
        canonical_url="https://psl.noaa.gov/thredds/dodsC/Datasets/godas/dbss_obil.YYYY.nc",
        access_url="https://psl.noaa.gov/thredds/dodsC/Datasets/godas/",
        access_method="opendap_ascii",
        format="opendap_ascii_grid",
        authority_level=AuthorityLevel.OPERATIONAL_INDEX,
        supported_metric_ids=("d20",),
        region="Niño 3.4 (5°S-5°N, 170°W-120°W) — area average",
        units="m (anomaly vs 1991-2020)",
        climatology="1991-2020 (computed from GODAS annual files)",
        temporal_resolution="monthly",
        expected_cadence="monthly",
        expected_release_window="Mediados del mes siguiente",
        typical_lag="10-20 days",
        freshness_slo="60 days",
        stale_after="75 days",
        revision_window="1-3 months",
        preliminary_policy="Latest 1-2 months may be preliminary",
        license="Public domain (NOAA)",
        attribution="NOAA/NCEP GODAS",
        request_budget=60,
        timeout=120.0,
        max_retries=3,
        operational_risk=OperationalRisk.MEDIUM_IRREGULAR,
    ),

    # --- Capa de autoridad oficial ---
    "noaa-cpc-enso-advisory": SourceProfile(
        source_id="noaa-cpc-enso-advisory",
        institution="NOAA / CPC",
        product="ENSO Alert System Status (official)",
        canonical_url="https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_advisory/ensodisc.shtml",
        access_url="https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_advisory/ensodisc.shtml",
        access_method="html_parse",
        format="html",
        authority_level=AuthorityLevel.OFFICIAL_AUTHORITY,
        supported_metric_ids=("basin_official_status",),
        region="Pacific ecuatorial (cuenca)",
        units="text (El Niño Advisory / La Niña Advisory / ENSO-Neutral / Watch)",
        climatology="N/A",
        temporal_resolution="monthly (second Thursday of each month)",
        expected_cadence="monthly",
        expected_release_window="Segundo jueves de cada mes",
        typical_lag="0-1 day after publication",
        freshness_slo="45 days",
        stale_after="60 days",
        revision_window="N/A (superseded by next discussion)",
        preliminary_policy="Official upon publication",
        license="Public domain (NOAA)",
        attribution="NOAA/CPC ENSO Diagnostic Discussion",
        request_budget=3,
        timeout=30.0,
        max_retries=3,
        operational_risk=OperationalRisk.HIGH_HTML,
    ),
    "enfen-imarpe-status": SourceProfile(
        source_id="enfen-imarpe-status",
        institution="ENFEN / IMARPE",
        product="Estado oficial El Niño Costero",
        canonical_url="https://siofen.imarpe.gob.pe/nivel2/indice-costero-el-nino-icen",
        access_url="https://enfen.imarpe.gob.pe/wp-json/wp/v2/posts?per_page=10&categories=28",
        access_method="json",
        format="wordpress_rest_json",
        authority_level=AuthorityLevel.OFFICIAL_AUTHORITY,
        supported_metric_ids=("coastal_official_status",),
        region="Costa peruana",
        units="text (Alerta / Vigilancia / Normal)",
        climatology="N/A",
        temporal_resolution="event-driven",
        expected_cadence="event-driven",
        expected_release_window="Tras reunión del comité ENFEN",
        typical_lag="Variable",
        freshness_slo="90 days",
        stale_after="120 days",
        revision_window="N/A (superseded by next comunicado)",
        preliminary_policy="Official upon publication",
        license="Atribución requerida (ENFEN/IMARPE)",
        attribution="ENFEN/IMARPE SIOFEN",
        request_budget=2,
        timeout=15.0,
        max_retries=2,
        fallback_source_ids=(),
        operational_risk=OperationalRisk.HIGH_HTML,
        unresolved_limitations="La API WordPress es estructurada, pero el texto del "
        "comunicado sigue requiriendo validación semántica. Fallback manual solo "
        "como último válido histórico, nunca como estado actual sin fecha.",
    ),
    "enfen-imarpe-document-assets": SourceProfile(
        source_id="enfen-imarpe-document-assets",
        institution="ENFEN / IMARPE",
        product="Official ENFEN communiqué and technical-report attachments",
        canonical_url="https://enfen.imarpe.gob.pe/",
        access_url="https://enfen.imarpe.gob.pe/wp-json/wp/v2/posts?per_page=10&categories=28",
        access_method="wordpress_rest_discovery_then_pdf",
        format="json_html_links_pdf",
        authority_level=AuthorityLevel.OFFICIAL_AUTHORITY,
        supported_metric_ids=("coastal_official_status", "icen"),
        region="Costa peruana",
        units="text; degC only when explicit ICEN value, unit and period are present",
        climatology="Defined by cited ENFEN technical note; must be captured per document",
        temporal_resolution="event-driven / monthly technical report",
        expected_cadence="event-driven",
        expected_release_window="After ENFEN committee meeting",
        typical_lag="same day to several days",
        freshness_slo="45 days",
        stale_after="75 days",
        revision_window="Superseded by next official communiqué",
        preliminary_policy="Official text on publication; extracted numeric facts require page evidence",
        license="Institutional publication; attribution required",
        attribution="ENFEN/IMARPE",
        request_budget=3,
        timeout=45.0,
        max_retries=2,
        fallback_source_ids=("enfen-imarpe-status",),
        operational_risk=OperationalRisk.HIGH_DOCUMENT,
        last_verified_at="2026-08-07",
        unresolved_limitations="PDF downloads can be slow; no OCR/LLM result may auto-publish without corroboration.",
    ),
    "imarpe-siofen-bdo": SourceProfile(
        source_id="imarpe-siofen-bdo",
        institution="IMARPE / SIOFEN",
        product="Boletín Diario Oceanográfico (BDO)",
        canonical_url="https://siofen.imarpe.gob.pe/boletines-e-informes/BDO",
        access_url="https://siofen.imarpe.gob.pe/boletines-e-informes/BDO",
        access_method="official_index_then_direct_pdf",
        format="html_pdf",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("peru_coastal_station_sst_daily",),
        region="Peruvian coastal monitoring stations",
        units="degC SST and anomaly when reported",
        climatology="Bulletin-specific; must be extracted from document metadata",
        temporal_resolution="daily bulletin",
        expected_cadence="business-day / operational",
        expected_release_window="Variable; no contractual release hour verified",
        typical_lag="1-5 days when published",
        freshness_slo="7 days",
        stale_after="14 days",
        revision_window="Superseded by later bulletin; corrections possible",
        preliminary_policy="Document observation; publish only validated station/date rows",
        license="Institutional publication; attribution required",
        attribution="IMARPE SIOFEN",
        request_budget=4,
        timeout=30.0,
        max_retries=2,
        operational_risk=OperationalRisk.HIGH_DOCUMENT,
        last_verified_at="2026-08-07",
        unresolved_limitations="Cloudflare returned 403 in this environment; do not bypass. Search discovery found assets only through 2026-05-12.",
    ),
    "imarpe-siofen-bs-tlp": SourceProfile(
        source_id="imarpe-siofen-bs-tlp",
        institution="IMARPE / SIOFEN",
        product="Boletín Semanal de la TSM en el Litoral Peruano (BS-TLP)",
        canonical_url="https://siofen.imarpe.gob.pe/boletines-e-informes/BS-TLP",
        access_url="https://siofen.imarpe.gob.pe/boletines-e-informes/BS-TLP",
        access_method="official_index_then_direct_pdf",
        format="html_pdf",
        authority_level=AuthorityLevel.RAPID_OBSERVATIONAL,
        supported_metric_ids=("peru_coastal_station_sst_weekly",),
        region="Peruvian coastal monitoring stations",
        units="degC SST and anomaly when reported",
        climatology="Bulletin-specific; must be extracted from document metadata",
        temporal_resolution="weekly bulletin",
        expected_cadence="weekly",
        expected_release_window="Weekly, variable release day",
        typical_lag="3-10 days",
        freshness_slo="14 days",
        stale_after="28 days",
        revision_window="Superseded by later bulletin; corrections possible",
        preliminary_policy="Document observation; publish only validated station/date rows",
        license="Institutional publication; attribution required",
        attribution="IMARPE SIOFEN",
        request_budget=4,
        timeout=30.0,
        max_retries=2,
        operational_risk=OperationalRisk.HIGH_DOCUMENT,
        last_verified_at="2026-08-07",
        unresolved_limitations="Cloudflare returned 403 in this environment; do not bypass. Search discovery found issue 23 dated 2026-06-10.",
    ),
}


def get_source(source_id: str) -> Optional[SourceProfile]:
    """Devuelve el SourceProfile para un source_id dado."""
    return SOURCES.get(source_id)


def all_source_ids() -> tuple[str, ...]:
    """Devuelve todos los source_ids registrados."""
    return tuple(SOURCES.keys())


def sources_for_metric(metric_id: str) -> tuple[str, ...]:
    """Devuelve los source_ids que soportan un metric_id dado."""
    return tuple(
        sid for sid, prof in SOURCES.items()
        if metric_id in prof.supported_metric_ids
    )
